yolo_model:

  config_file:
    name: yolov3-416.cfg
  weight_file:
    name: yolov3-416_50700.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Parking_A
      - Parking_B
      - Go
      - Stop
